runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:R1AgPWVbIpUzQvE3qKnp2xRGmXp9Wr5gFRr2BojCne0=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie